package com.baeldung.drools.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("customer")
public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label(value = "years")
	private java.lang.Integer years;
	@org.kie.api.definition.type.Label(value = "discount")
	private java.lang.Integer discount;

	public Customer() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Integer getYears() {
		return this.years;
	}

	public void setYears(java.lang.Integer years) {
		this.years = years;
	}

	public java.lang.Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(java.lang.Integer discount) {
		this.discount = discount;
	}

	public Customer(java.lang.String type, java.lang.Integer years,
			java.lang.Integer discount) {
		this.type = type;
		this.years = years;
		this.discount = discount;
	}

}